name: EconomicsPlugin
version: '${project.version}'
main: io.github.hidingincode.economicsplugin.EconomicsPlugin
api-version: 1.15
authors: [ HidingInCode ]
description: Basic economics plugin by HidingInCode
website: https://github.com/HidinginCode
commands:
  getMoney:
    description: Shows you how much money you have
    usage: /getmoney
    aliases: money

  setMoney:
    description: Sets the money of your target to a specific amount
    usage: /setmoney <Player> <Amount>

  giveMoney:
    description: Give money to another player
    usage: /givemoney <Player> <Amount>
